# Generated by Django 4.0.4 on 2022-04-19 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('establish_date', models.DateField(default=datetime.date(2022, 4, 20))),
                ('located_at', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('site_url', models.TextField()),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphan_name', models.CharField(max_length=200)),
                ('orphan_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('admitted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_type', models.CharField(max_length=300)),
                ('event_date', models.DateField(default=datetime.date(2022, 4, 20))),
                ('event_time', models.TimeField(default=datetime.time(0, 48, 11, 57195))),
                ('venue', models.TextField()),
                ('organised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orphanage')),
            ],
        ),
    ]
