# Generated by Django 4.0.4 on 2022-04-20 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_description_alter_event_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphanage',
            old_name='located_at',
            new_name='address',
        ),
        migrations.AddField(
            model_name='orphanage',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(18, 22, 11, 765326)),
        ),
    ]
