# Generated by Django 4.0.4 on 2022-04-20 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_event_event_time_alter_orphanage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(18, 47, 54, 371084)),
        ),
    ]
