# Generated by Django 4.0.4 on 2022-04-21 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_admitted_to_orphan_admit_to_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbacks',
            new_name='Feedback',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(21, 45, 22, 715920)),
        ),
    ]
