# Generated by Django 4.0.4 on 2022-04-22 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_feedbacks_feedback_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date(2022, 4, 22)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(19, 41, 46, 778983)),
        ),
        migrations.AlterField(
            model_name='orphanage',
            name='establish_date',
            field=models.DateField(default=datetime.date(2022, 4, 22)),
        ),
    ]
