# Generated by Django 4.0.4 on 2022-04-22 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_description_alter_event_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(21, 20, 9, 814228)),
        ),
    ]
